name: recsys-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.3.1
  - expat=2.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - graphite2=1.3.14
  - harfbuzz=12.1.0
  - icu=75.1
  - joblib=1.5.2
  - kiwisolver=1.4.8
  - kmedoids=0.5.4
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.3
  - libclang13=21.1.3
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.1
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libllvm21=21.1.3
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=18.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libvulkan-loader=1.4.313.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.12.2
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lmdb=0.9.31
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - ncurses=6.5
  - numpy=2.3.3
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=21.3
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pyparsing=3.0.4
  - pyside6=6.9.3
  - python=3.14.0
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.3
  - readline=8.2
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - setuptools=78.1.1
  - six=1.17.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.5.1
  - tqdm=4.63.0
  - tzdata=2025b
  - wayland=1.24.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - zlib=1.3.1
  - zstd=1.5.7
